[pytest]
filterwarnings =
    ignore:invalid escape sequence:DeprecationWarning
    ignore:nopython is set for njit and is ignored:RuntimeWarning
    ignore:distutils Version classes are deprecated:DeprecationWarning
    ignore:`np.float` is a deprecated alias:DeprecationWarning
    ignore:np.float is a deprecated alias:DeprecationWarning
    ignore:converting a masked element to nan:UserWarning
